# Site settings
title: the padded cell
email: ba@sanitarium.se
description: ""
baseurl: ""
url: "http://sanitarium.se"
twitter_username: gaqzi
github_username:  gaqzi
facebook_username:
timezone: UTC
github_base_url: https://github.com/gaqzi/sanitarium.se/blob/master/

# Build settings
markdown: kramdown
redcarpet:
  extensions:
    - footnotes
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
highlighter: pygments
permalink: pretty
paginate: 100
paginate_path: /page/:num
exclude:
  - .idea/
  - bin/*
  - blog.iml
  - css/*.min.css
  - css/bootstrap.css
  - css/clean-blog.css
  - css/syntax.css
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - js/bootstrap.js
  - js/bootstrap.min.js
  - js/clean-blog.js
  - js/clean-blog.min.js
  - js/jquery.js
  - js/jquery.min.js
  - less
  - LICENSE
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - README.md

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
