# Site settings
title: the padded cell
email: ba@sanitarium.se
description: ""
baseurl: ""
url: "https://sanitarium.se"
twitter_username: gaqzi
github_username:  gaqzi
mastodon:
  username: gaqzi
  instance: hachyderm.io
facebook_username:
timezone: UTC
github_base_url: https://github.com/gaqzi/sanitarium.se/blob/master/

social:
  name: björn
  links:
    - https://hackyderm.io/@gaqzi
    - https://github.com/gaqzi
    - https://speakerdeck.com/gaqzi

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/mastodon_webfinger
  - jekyll-seo-tag

defaults:
  - scope:
      path: presentations/reveal/**
    values:
      sitemap: false

# Build settings
markdown: kramdown
redcarpet:
  extensions:
    - footnotes
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
permalink: pretty
paginate: 100
paginate_path: /page/:num
exclude:
  - .idea/
  - .gitignore
  - bin/*
  - blog.iml
  - css/*.min.css
  - css/bootstrap.css
  - css/clean-blog.css
  - css/syntax.css
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - js/bootstrap.js
  - js/bootstrap.min.js
  - js/clean-blog.js
  - js/clean-blog.min.js
  - js/jquery.js
  - js/jquery.min.js
  - less
  - LICENSE
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - README.md
