baseURL = 'https://sanitarium.se/'
languageCode = 'en-us'
title = 'the padded cell'
theme = 'sanitarium'

defaultContentLanguage = "en"

cascade = [
  { _target = { path = "/archive/**" }, outputs = ["HTML"], sitemap = { disable = true } },
]

# URL structure 
[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  archive = "/archive/:year-:month-:day-:slug/"

  tag = "/tags/:slug/"
  author = "/author/:slug/"

# Output formats
[outputs]
  home = ["HTML", "RSS", "PostData"]
  page = ["HTML", "Banner"]
  section = ["HTML", "RSS"]

# RSS settings
[outputFormats.RSS]
  baseName = "feed"

# Pagination
paginate = 10
paginatePath = "/page/:num"

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Enable emojis
enableEmoji = true

# Taxonomies
[taxonomies]
  tag = "tags"
  author = "authors"
#  category = "categories"

# Theme-specific settings
[params]
  # Social media links
  github = "https://github.com/gaqzi"
  mastodon = "https://hachyderm.io/@gaqzi"
  feed = "/feed.xml"
  mastodonHandle = "@gaqzi@hachyderm.io"

  # SEO settings
  defaultImage = "/img/site-default-image.jpg"  # Default image for social media when not specified in post
  twitterAuthor = "gaqzi"  # Twitter handle without @
  favicon = "/favicon.ico"

  # Site settings
  description = "ramblings of a technical nature"
  mainSections = ["blog", "til"]

  # Theme appearance
  enableCodeHighlighting = true
  footerLogo = "/img/old-logo.gif"
  footerLogoAlt = "padded cell logo"

  # Author information
  author = "björn"

  # Timezone
  timeZone = "UTC"

# Sitemap config
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup settings
[markup]
  [markup.highlight]
    codeFences = true
    style = "zenburn"
    noClasses = false

[markup.goldmark.renderer]
  unsafe = true  # Allow HTML in markdown
