baseURL = 'https://sanitarium.se/'
languageCode = 'en-us'
title = 'the padded cell'
theme = 'sanitarium'

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Enable emojis
enableEmoji = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Theme-specific settings
[params]
  # Social media links
  github = "https://github.com/gaqzi"
  mastodon = "https://hachyderm.io/@gaqzi"
  feed = "/index.xml"
  
  # Site settings
  siteName = "the padded cell"
  description = "Personal blog of Björn"
  mainSections = ["posts"]
  
  # Theme appearance
  enableCodeHighlighting = true
  footerLogo = "/img/old-logo.gif"
  footerLogoAlt = "padded cell logo"
  
  # Author information
  author = "björn"