baseURL = 'https://sanitarium.se/'
languageCode = 'en-us'
title = 'the padded cell'
theme = 'sanitarium'

defaultContentLanguage = "en"

cascade = [
  { _target = { path = "/archive/**" }, outputs = ["HTML"], sitemap = { disable = true } },
  { _target = { path = "/til/**"}, full = true },
  { _target = { path = "/link/**"}, full = true },
  { _target = { path = "/scrap/**"}, full = true },
]

# URL structure 
[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  archive = "/archive/:year-:month-:day-:slug/"

  tag = "/tags/:slug/"
  author = "/author/:slug/"
  daily = "/daily/:slug/"

# Output formats
[outputs]
  home = ["HTML", "RSS", "PostData"]
  page = ["HTML", "Banner"]
  section = ["HTML", "RSS"]

# RSS settings
[outputFormats.RSS]
  baseName = "feed"

# Pagination
[pagination]
  pagersize = 20

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Enable emojis
enableEmoji = true

[menus]
  [[menus.main]]
    name = 'TILs'
    pageRef = '/til/'
    weight = 10

  [[menus.main]]
    name = 'Crumbs'
    pageRef = '/crumb/'
    weight = 20

  [[menus.main]]
    name = 'Scraps'
    pageRef = '/scrap/'
    weight = 30

  [[menus.main]]
    name = 'Links'
    pageRef = '/link/'
    weight = 40

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog/'
    weight = 50

  [[menus.main]]
    name = 'Series'
    pageRef = '/series/'
    weight = 60
    [menus.main.params]
      divider = true

  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 70

  [[menus.main]]
    name = 'Now'
    pageRef = '/now/'
    weight = 80

#  [[menus.main]]
#    name = 'Subscribe'
#    pageRef = '/subscribe/'
#    weight = 90
#    [menus.main.params]
#      divider = true

# Taxonomies
[taxonomies]
  tag = "tags"
  author = "authors"
  daily = "daily"
  series = "series"
  link = "links"
  crumb = "crumbs"
  scrap = "scraps"
#  category = "categories"

# Theme-specific settings
[params]
  # Social media links
  github = "https://github.com/gaqzi"
  mastodon = "https://hachyderm.io/@gaqzi"
  feed = "/feed.xml"
  mastodonHandle = "@gaqzi@hachyderm.io"

  # SEO settings
  defaultImage = ""  # Default image for social media when not specified in post
  twitterAuthor = "gaqzi"  # Twitter handle without @
  favicon = "/favicon.ico"

  # Site settings
  description = "ramblings of a technical nature"
  mainSections = ["blog", "til", "link", "crumb", "scrap"]
  bannerSections = ["blog", "crumb"]

  # Theme appearance
  enableCodeHighlighting = true
  footerLogo = "/img/old-logo.gif"
  footerLogoAlt = "padded cell logo"

  # Author information
  author = "björn"

  # Location
  defaultLocation = "Sweden"

  # Timezone
  timeZone = "UTC"

# Sitemap config
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup settings
[markup]
  [markup.highlight]
    codeFences = true
    style = "zenburn"
    noClasses = false

[markup.goldmark.renderer]
  unsafe = true  # Allow HTML in markdown
