baseURL = 'https://sanitarium.se/'
languageCode = 'en-us'
title = 'the padded cell'
theme = 'sanitarium'

# URL structure 
[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  archive = "/blog/:year/:month/:day/:slug/"

# Output formats
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

# RSS settings
[outputFormats.RSS]
  baseName = "feed"

# Pagination
paginate = 100
paginatePath = "/page/:num"

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Enable emojis
enableEmoji = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Theme-specific settings
[params]
  # Social media links
  github = "https://github.com/gaqzi"
  mastodon = "https://hachyderm.io/@gaqzi"
  feed = "/feed.xml"
  mastodonHandle = "@gaqzi@hachyderm.io"
  
  # SEO settings
  defaultImage = "/img/site-default-image.jpg"  # Default image for social media when not specified in post
  twitterAuthor = "gaqzi"  # Twitter handle without @
  favicon = "/favicon.ico"
  
  # Site settings
  siteName = "the padded cell"
  description = "Personal blog of Björn about programming, technology, and automation"
  mainSections = ["posts"]
  
  # Theme appearance
  enableCodeHighlighting = true
  footerLogo = "/img/old-logo.gif"
  footerLogoAlt = "padded cell logo"
  
  # Author information
  author = "björn"
  
  # Timezone
  timeZone = "UTC"

# Sitemap config
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup settings
[markup]
  [markup.highlight]
    style = "zenburn"
    
  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML in markdown
