#!/bin/bash
# This script will read the specified file and update it the web,
# assumed to be a temporary file.
# Then the update as returned by n8n is stored in the second argument,
# OR if empty, into the default workflow file.
source .env

: ${workflow_id:=TCuBWAGiOB1WpXVy}
: ${N8N_HOST:=http://localhost:5678}

# Default to storing in the workflow we have
OUTPUT=$2
if [ -z "$OUTPUT" ]; then
  OUTPUT=bjorn.now-feed-distribution.json
fi

if [ ! -s "$1" ] ; then
  echo "file '$1' does not exist or is empty" >&2
  exit 1
fi

# Only update the workflow if the `.versionId` ISN'T the same as the server,
# because we're downloading the workflow and then applying our updates to it.
# This intends to avoid overwriting anything we didn't expect.
localVersion=$(jq -r '.versionId' "$1")
serverVersion=$(workflow_id=$workflow_id ./get-workflow 2>/dev/null | jq -r '.versionId')
if [ "$localVersion" != "$serverVersion" ]; then
  echo "The local workflow file ($1) is stale to the server version" >&2
  echo "  local version : ${localVersion}" >&2
  echo "  server version: ${serverVersion}" >&2
  echo >&2
  echo "Hint: Pull down the latest version as and recreate:" >&2
  echo "  ./get-workflow > bjorn.now-feed-distribution.json" >&2
  echo "  ./create-update" >&2

  exit 2
fi

cat $1 | jq '{
           name,
           nodes,
           connections,
           settings
         }' | \
  curl -X PUT "${N8N_HOST}/api/v1/workflows/${workflow_id}" \
    -H "X-N8N-API-KEY: ${N8N_API_KEY}" \
    -H "Content-Type: application/json" \
    -d @- |
    jq > $OUTPUT
