---
name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: |
            ./.devcontainer/docker-compose.yaml
            ./.devcontainer/docker-compose.ci.yaml
          up-flags: --exit-code-from jekyll

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: |
            ./.devcontainer/docker-compose.yaml
            ./.devcontainer/docker-compose.ci.yaml
          up-flags: --exit-code-from jekyll

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/
          retention-days: 1
          if-no-files-found: error

  deployment:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: production
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: site
          path: _site/

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan cell.sanitarium.se >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.DEPLOY_SSH }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: make _deploy

      - name: Ping
        run: make ping
