---
name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: actions/setup-node@v2
        with:
          node-version: lts/erbium
          cache: npm

      - uses: actions/cache@v2
        with:
          path: img/banners/*.gen.png
          key: ${{ runner.os }}-banners-${{ hashFiles('_plugins/banner_creator.rb') }}

      - name: Build
        run: >
          make build

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site/
          retention-days: 1
          if-no-files-found: error

  deployment:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: site

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan cell.sanitarium.se >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.DEPLOY_SSH }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: make _deploy

      - name: Ping
        run: make ping
